"""empty message

Revision ID: ba2513a66d97
Revises: 
Create Date: 2022-05-12 19:54:31.798764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2513a66d97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('postcode', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('toaletaAkt', sa.Boolean(), nullable=True),
    sa.Column('toaletaElektr', sa.Boolean(), nullable=True),
    sa.Column('parking', sa.Boolean(), nullable=True),
    sa.Column('winda', sa.Boolean(), nullable=True),
    sa.Column('brakProgow', sa.Boolean(), nullable=True),
    sa.Column('swobodnyAkt', sa.Boolean(), nullable=True),
    sa.Column('swobodnyElektr', sa.Boolean(), nullable=True),
    sa.Column('drzwiAkt', sa.Boolean(), nullable=True),
    sa.Column('drzwiElektr', sa.Boolean(), nullable=True),
    sa.Column('rownyTeren', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_places_id'), 'places', ['id'], unique=False)
    op.create_index(op.f('ix_places_lat'), 'places', ['lat'], unique=False)
    op.create_index(op.f('ix_places_lng'), 'places', ['lng'], unique=False)
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_id'), 'points', ['id'], unique=False)
    op.create_index(op.f('ix_points_lat'), 'points', ['lat'], unique=False)
    op.create_index(op.f('ix_points_lng'), 'points', ['lng'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_lng'), table_name='points')
    op.drop_index(op.f('ix_points_lat'), table_name='points')
    op.drop_index(op.f('ix_points_id'), table_name='points')
    op.drop_table('points')
    op.drop_index(op.f('ix_places_lng'), table_name='places')
    op.drop_index(op.f('ix_places_lat'), table_name='places')
    op.drop_index(op.f('ix_places_id'), table_name='places')
    op.drop_table('places')
    # ### end Alembic commands ###
